spring:
  main.banner-mode: 'off'

  thymeleaf.cache: false

  datasource.url: jdbc:h2:./db;AUTO_SERVER=TRUE
  h2.console.enabled: true

  resources:
    cache.period: 0
    chain.strategy.fixed:
      enabled: true
      version: '@git.commit.id.abbrev@'

  messages:
    cache-duration: 0
    encoding: ISO-8859-1
    fallback-to-system-locale: false
    use-code-as-default-message: true
    basename: messages,classpath*:/ValidationMessages,classpath*:/org/hibernate/validator/ValidationMessages

  mvc.locale: en_US

  liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

server.error.include-stacktrace: on-trace-param

logging.level.org.jooq.Constants: ERROR
